### DISCUSSION TITLE
docker-compose - selenium

### DISCUSSION THREAD

**Discussion by jifox** [nautobot/nautobot#632] [General]
Is publishing of the port 4444 to the host machine really needed? 

```yaml
---
version: "3"
services:
  ...
  selenium:
    image: selenium/standalone-firefox:latest
    ports: 
      - "4444:4444"
    shm_size: 2g
```

If its not required to be published on the host machine it should be replaced with: 

```yaml
  selenium:
    image: selenium/standalone-firefox:latest
    expose: 
      - "4444"
    shm_size: 2g
```

see: [Compose File Reference](https://docs.docker.com/compose/compose-file/compose-file-v3/#expose):
>Expose ports without publishing them to the host machine - they’ll only be accessible to linked services. Only the internal port can be specified.
>
