### ISSUE TITLE
include various data sets with Nautobot for testing and developing against Nautobot

### ISSUE THREAD

**Issue by jedelman8** [nautobot/nautobot#113]
### Proposed Functionality

Include a few different data sets in the GitHub repository that users can load into Nautobot when they are just trying it out or developing against Nautobot.  We're looking for anyone willing to share their data. Would love different verticals (retail, Enterprise, Cloud, Telco, etc.) and would love even more if some are at large scale.  

The core team can also help automate the process to anonymize the data too.

### Use Case

Simplify exploring Nautobot, developing against Nautobot, and replicating real environments to troubleshoot and diagnose bugs quicker.

This could then be used by `nautobot-lab` as well.

**Comment by jifox** [comment]
Hi @glennmatthews 

What about implementing a parser for yaml data and use pynautobot to import data to nautobot.

This will allow manual editing or migrate existing data from e.g ansible via jinja templates. Also this could be a valuable example for using pynautobot.

What are your thoughts?

```yaml
---
nb_tenant_groups:
  "tenancy.tenant_groups":                         # pynautobot object name module
    unique_fields: ["slug"]                        # Fieldnames used ti select a specific record
    records:                                       # List of Dict to add 
      - name: "Foo-PLC"
        slug: "foo-plc"
        description: "Foo-PLC Example Company"

nb_tenants:
  "tenancy.tenant":
    unique_fields: ["slug"]
    records:
      - name: "Foo-PLC-AU"
        slug: "tenant-au"
        description: "Foo-PLC - Australia"
        lookups:                                # foreign values
          "group":                              # fieldnames in tenant used to store the lookup result
            "tenancy.tenant_groups":            # --> parse recursivly and assig to field "group"
              unique_fields: ["slug"]
              records:
                - slug: foo-plc
      - name: "Foo-PLC-GR"
        slug: "tenant-gr"
        description: "Foo-PLC - Greece"
        lookups:
          "group":
            "tenancy.tenant_groups":
              unique_fields: ["slug"]
              records:
                - slug: foo-plc
      - name: "Foo-PLC-CA"
        slug: "tenant-ca"
        description: "Foo-PLC - California"
        lookups:
          "group":
            "tenancy.tenant_groups":
              unique_fields: ["slug"]
              records:
                - slug: foo-plc
```
