### ISSUE TITLE
PowerFeedTypeChoices default value in OpenAPI spec is of incorrect type

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot#3092]
### Environment
* Nautobot version (Docker tag too if applicable): 1.5.7
* Python version: 3.9
* Database platform, version: Postgresql
* Middleware(s): -

### Steps to Reproduce
1. `inv build start`
2. `wget http://localhost:8080/api/swagger --output-document swagger.yml`
3. Browse to what for me is line 108759, the path is `components.schemas.PatchedBulkWritablePowerFeedRequest.properties.type`

### Expected Behavior
The `default` field for the type should be of type `string`, because that is what the referenced component (`$ref: '#/components/schemas/PowerFeedTypeChoices'`) specifies for its type. See [OpenAPI docs](https://swagger.io/docs/specification/describing-parameters/#default) for the default parameter:
> The value type must be the same as the parameter’s data type

### Observed Behavior

The type is a JSON object / dictionary instead of `string`:
```
        type:
          allOf:
          - $ref: '#/components/schemas/PowerFeedTypeChoices'
          default:
            value: primary
            label: Primary
```

where

```
    PowerFeedTypeChoices:
      type: string  # this is what the type _should_ be
      enum:
      - primary
      - redundant
```
