### ISSUE TITLE
dev environment postgres health check emitting errors

### ISSUE THREAD

**Issue by gsnider2195** [nautobot/nautobot#3422]
### Environment
* Nautobot version (Docker tag too if applicable): v1.5.12
* Python version: v3.7
* Database platform, version: postgres
* Middleware(s):

### Steps to Reproduce
1. run the development environment `invoke debug` using `docker-compose.postgres.yml` for the `db` container

### Expected Behavior
No errors are emitted from the database container

### Observed Behavior

Database container logs the following messages 

```
nautobot-db-1             | 2023-03-14 17:08:43.726 UTC [87] FATAL:  role "root" does not exist
nautobot-db-1             | 2023-03-14 17:08:48.800 UTC [96] FATAL:  role "root" does not exist
nautobot-db-1             | 2023-03-14 17:08:53.875 UTC [105] FATAL:  role "root" does not exist
```

Adding `PGUSER=nautobot` to the `db` container environment fixes this.

**Comment by u1735067** [comment]
If it can be useful:
```
    healthcheck:
      test: pg_isready --username=$$POSTGRES_USER --dbname=$$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 300s  # In case DB needs recovery, allow 5 mins of failures
```
