### ISSUE TITLE
DeviceFilterSet attributes being stripped of options

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot#4377]
### Environment
* Nautobot version (Docker tag too if applicable): 2.0-rc2
* Python version: 3.11
* Database platform, version: latest
* Middleware(s): N/A

I attempted to look on 1.5 or 1.6 but the demo instances weren't immediately loading to see if this is 1.x or not. 

### Steps to Reproduce
1. Go to https://next.demo.nautobot.com/api/docs/#/dcim/dcim_devices_list
2. Observe has_device_bays, created, last_updated, etc. 

### Expected Behavior

The attributes to match up to their type, such as DateTime, Boolean, Integer, etc.. as shown in the device-types api

<img width="643" alt="image" src="https://github.com/nautobot/nautobot/assets/9260483/315068ea-fb6e-490e-846b-b258a630e628">

### Observed Behavior

Everything is defaulting to char type.

<img width="698" alt="image" src="https://github.com/nautobot/nautobot/assets/9260483/63143b5e-c896-4e92-8dbe-291e4e34fe77">

**Comment by itdependsnetworks** [comment]
The same seems to be true for virtual machines.

**Comment by glennmatthews** [comment]
Can confirm that the OpenAPI schema differs between Device and DeviceType in `next`, e.g.:

```yaml
      - name: has_console_ports
        required: false
        in: query
        description: Has console ports
        schema:
          type: string
```

versus:

```yaml
      - in: query
        name: has_console_port_templates
        schema:
          type: boolean
        description: Has console port templates
```
