### ISSUE TITLE
Custom Dockerfile Stage Tasks

### ISSUE THREAD

**Issue by snaselj** [nautobot/nautobot#4408]
### Proposed Changes

Allow testing of individual Dockerfile build stages.

Example usage:

```bash
# Build the stage and tag it as "localhost/nautobot-system-dependencies:local-py3.8"
invoke custom-build --target system-dependencies
# Run bash inside the container
invoke custom-cli --target system-dependencies
```

### Justification

Using the following during the Dockerfile development, curious whether I can add it to Nautobot tasks:

`development/docker-compose.custom.yml`

```yaml
---
services:
  custom:
    build:
      args:
        PYTHON_VER: "${PYTHON_VER}"
      context: ../
      dockerfile: docker/Dockerfile
      target: $TARGET
    image: "localhost/nautobot-$TARGET:local-py${PYTHON_VER}"
    entrypoint: []
    env_file:
      - dev.env
```

`tasks.py` addition:

```python
def _get_custom_env(context, target):
    return {
        "COMPOSE_ANSI": "false",
        "COMPOSE_FILE": "development/docker-compose.custom.yml",
        "COMPOSE_IGNORE_ORPHANS": "true",
        "COMPOSE_PROJECT_NAME": context.nautobot.project_name,
        "PYTHON_VER": context.nautobot.python_ver,
        "TARGET": target,
    }


@task(help={"target": "Target to build (dev, final-dev, final, ...)"})
def custom_build(context, cache=True, pull=False, target="dev"):
    """Build a custom Nautobot Docker image."""
    command = [
        "docker compose build",
        "--pull" if pull else "",
        "--no-cache" if not cache else "",
        "--",
        "custom",
    ]
    context.run(" ".join(command), env=_get_custom_env(context, target))


@task(help={"target": "Target to build (dev, final-dev, final)"})
def custom_cli(context, target="dev"):
    """Build a custom Nautobot Docker image."""
    context.run("docker compose run --rm -- custom bash", env=_get_custom_env(context, target), pty=True)
```
