### ISSUE TITLE
Tree Model Inheritance Constructs

### ISSUE THREAD

**Issue by itdependsnetworks** [nautobot/nautobot#4413]
### As ...

Ozzie - Operator

### I want ...

The ability to understand information about the current tree object, based on business logic on what I care about.

### So that ...

I can get the feeling of M2M relationships more strategically. 

### I know this is done when...

There is a method, such as described in the below yaml.

```yaml
locations:
  - type: floor
     parent_type: site
     inherit_attributes:  {{ obj.contact_name }}
     inherit_logic:  {% if obj.cf_business_unit in ["retail", "warehouses"] %}
  - type: building
     parent_type: site
     inherit_attributes:  {{ obj.vlan_id }}
     inherit_logic:  {% if obj.cf_building_name in parent.cf_vlans_spanned %}
```

I have the ability to see this data in the UI, and **ideally** can access the data via the ORM, REST API, and GRAPHQL with a custom method, such as `obj.get_tree_related_info`. 

### Optional - Feature groups this request pertains to.

- [ ] Automation
- [ ] Circuits
- [ ] DCIM
- [ ] IPAM
- [ ] Misc (including Data Sources)
- [ ] Organization
- [ ] Plugins (and other Extensibility)
- [ ] Security (Secrets, etc)
- [ ] Image Management
- [X] UI/UX
- [ ] Documentation
- [ ] Other (not directly a platform feature)
