### ISSUE TITLE
SAML/Shibboleth Authentication

### ISSUE THREAD

**Issue by networkautomaniac** [nautobot/nautobot#5369]
### Environment
* Nautobot version (Docker tag too if applicable): 2.1.1
* Python version: 3.9
* Database platform, version: MySQL 8.0.35
* Middleware(s):

### Steps to Reproduce
1. Installed nautobot[sso] and all other necessary packages.
2. Applied SSO/SAML configuration to nautobot_config.py
```
AUTHENTICATION_BACKENDS:
    - "social_core.backends.saml.SAMLAuth"
    - "nautobot.core.authentication.ObjectPermissionBackend"
  SECURE_SSL_REDIRECT: true
  SECURE_PROXY_SSL_HEADER: ('HTTP_X_FORWARDED_PROTO', 'https')
  SOCIAL_AUTH_SAML_HTTPS: true
  SOCIAL_AUTH_SAML_SP_ASSERTION_CONSUMER_SERVICE:
    url: "https://<url>"
  SOCIAL_AUTH_SAML_SP_ENTITY_ID: "https://<url>"
  SOCIAL_AUTH_SAML_SP_PUBLIC_CERT: ""
  SOCIAL_AUTH_SAML_SP_PRIVATE_KEY: ""
  SOCIAL_AUTH_SAML_ORG_INFO:
    en-US:
      name: "Nautobot"
      displayname: "Nautobot"
      url: "https://<url>"
  SOCIAL_AUTH_SAML_TECHNICAL_CONTACT:
    givenName: "Helpdesk"
    emailAddress: "email@example.com"
  SOCIAL_AUTH_SAML_SUPPORT_CONTACT:
    givenName: "Helpdesk"
    emailAddress: "email@example.com"
  SOCIAL_AUTH_SAML_ENABLED_IDPS:
    shibboleth:
      entity_id: "https://<url>/idp/shibboleth"
      url: "https://<url>/idp/profile/SAML2/Redirect/SSO"
      x509cert: "cert-here"
      force_authn: true
      allow_unsolicited: false
      requested_authn_context: false
      attr_user_permanent_id: "mail"
      attr_username: "mail"
      attr_email: "mail"
      attr_first_name: "givenName"
      attr_last_name: "sn"
```

Using SAML-tracer the following is shown:

```
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                    ID="ONELOGIN_fa6f2fa225f8e5847c69e93e7168b175405bef67"
                    Version="2.0"
                    ProviderName="Nautobot"
                    IssueInstant="2024-02-29T17:08:20Z"
                    Destination="https://<url>/idp/profile/SAML2/Redirect/SSO"
                    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                    AssertionConsumerServiceURL="http://<url>/complete/saml/"
                    >
```
`AssertionConsumerServiceURL` is shown as http and not https.`

Expected to proceed to login.

Presented with a page stating:
```
Shibboleth - Unable to Respond The login service was unable to identify a compatible way to respond to the requested application. This is generally due to a misconfiguration on the part of the application and should be reported to the application's support team or owner.
```
