### ISSUE TITLE
config context in git repo using device_types is not mapped in nautobot

### ISSUE THREAD

**Issue by jlixfeld** [nautobot/nautobot#562]
### Environment
* Python version: 3.8.2
* Nautobot version: 1.0.2

### Steps to Reproduce
1.  Configure nautobot to point to git repo supporting `config_context` data type.
2. Create `test.yaml`, include `device_type`:
```
_metadata:
  name: "Apply Me To The Mars"
  weight: 1000
  is_active: true
  device_types:
    - model: DCS-7280CR3-32D4
  roles:
    - slug: pe
    - slug: bdr
mars:
  - 998
 ```
3. Commit `test.yaml` to repo
4. Sync repo with nautobot

### Expected Behavior
Review `[nautobot] Apply Me To The Mars` config context in Nautobot should display all mappings configured in `test.yaml`

### Observed Behavior
All mappings except `device_types` are mapped.

Reviewing the change log after the repo sync shows `device_types` as an empty list.
