### ISSUE TITLE
Dark mode is not properly announced to the browser

### ISSUE THREAD

**Issue by u1735067** [nautobot/nautobot#5890]
### Environment
* Nautobot version (Docker tag too if applicable): 1.6.23 / 2.x (captures below done on 2.x but bug was found on 1.6.x)

### Steps to Reproduce
1. Browse to a Nautobot instance supporting dark mode (like https://demo.nautobot.com/) using Vivaldi set to Dark mode + "Force a dark theme on all websites"

I guess the result would be the similar with any extension to force dark mode while the browser already asks for dark mode.

### Expected Behavior

The dark mode is applied: 
<img width="1164" alt="image" src="https://github.com/nautobot/nautobot/assets/1735067/e4f97fdc-19af-4b55-bcab-b8e17857b09e">

### Observed Behavior

Light mode is always ok:
<img width="1165" alt="image" src="https://github.com/nautobot/nautobot/assets/1735067/600d4fbd-68bf-42e1-86a0-7ac6b9a4ce63">

But forced dark mode is Nautobot dark mode + browser/extension forced dark mode applied on top -> ~"gray light" mode
<img width="1165" alt="image" src="https://github.com/nautobot/nautobot/assets/1735067/a5a86079-18fa-405a-9802-ecc2875c958d">

### Fix

This can be fixed by properly announcing dark mode to the browser/extension, so it does not try to reapply dark mode over dark mode:
<img width="1164" alt="image" src="https://github.com/nautobot/nautobot/assets/1735067/3e87c36f-5d5e-4adf-aa33-b7d0d14cc2df">

More informations at https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/, 2 options:
```css
:root {
  color-scheme: light dark;
}
```

```html
<meta name="color-scheme" content="dark light">
```

Edit: another option related to Nautobot's dark.css, but this ones makes a small dark flash when switching from light to dark in preferences, as the attribute indicating this is a dark scheme is found by the browser after the css is loaded:
```css
html[data-theme="dark"] {
  // ..
  color-scheme: dark;
}
```

**Comment by HanlinMiao** [comment]
Thank you very much for submitting the issue and the super helpful triage. We will definitely look into it.

**Comment by smk4664** [comment]
This works, but has one side-effect that I haven't really dug into yet.  Form Buttons are shiny, see screenshots below.

![image](https://github.com/user-attachments/assets/441d0888-799e-4f0c-9374-775706ff94d5)
![image](https://github.com/user-attachments/assets/b3938b68-6e93-4ca3-8ad8-aa2f72e3cc93)

**Comment by smk4664** [comment]
> This works, but has one side-effect that I haven't really dug into yet. Form Buttons are shiny, see screenshots below.
> 
> ![image](https://private-user-images.githubusercontent.com/17092348/350531402-441d0888-799e-4f0c-9374-775706ff94d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTc0NDIsIm5iZiI6MTcyMTQxNzE0MiwicGF0aCI6Ii8xNzA5MjM0OC8zNTA1MzE0MDItNDQxZDA4ODgtNzk5ZS00ZjBjLTkzNzQtNzc1NzA2ZmY5NGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE5MjU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZDAyMDY5MDlmNjU5M2FkNzU2YmI4MTc5MjEzOWNiYTI1YTVjODU4OTFhYzU3YmI0ZWFhZTdjNGI0ZmYzODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SKBynmHytFYzwbPmyxtsZCOChdgRFr3ncWHSshJus0A) ![image](https://private-user-images.githubusercontent.com/17092348/350531525-b3938b68-6e93-4ca3-8ad8-aa2f72e3cc93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTc0NDIsIm5iZiI6MTcyMTQxNzE0MiwicGF0aCI6Ii8xNzA5MjM0OC8zNTA1MzE1MjUtYjM5MzhiNjgtNmU5My00Y2EzLThhZDgtYWEyZjcyZTNjYzkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE5MjU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwZmYwYTg3NmRmZTRjMWI2Y2VjNmJjZGVhMGFhZTEyYjhiYTExZTg0YjE0MDgwOTdmMzQ2ODVmMTM5YTFhNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hwy1XIQ_Ls5QZ6wu1oLoHFcAgjUBHYGA90EIMPrIqOU)

This is actually just an issue on Safari, and without this change, the button still renders incorrectly, just less noticeable.
![image](https://github.com/user-attachments/assets/b3d7dc76-8526-49c2-8e15-83229dbaa73c)

**Comment by u1735067** [comment]
```css
:root {
    color-scheme: light dark;
}
html[data-theme="light"] {
    color-scheme: light dark;
}
html[data-theme="dark"] {
    color-scheme: dark light;
}
html[data-theme="dark"] {
    button, input, select, textarea, optgroup { /* from normalize.less */
        &:not( /* Exclude things already handled */
            /* General exceptions */
            img, .badge, .btn, .label, .color-block, .select2-selection__choice,
            #select2-id_color-results, #select2-id_color-container,
            /* Swagger exceptions */
            .swagger-ui *,
            /* GraphiQL exceptions */
            .graphiql-container *,
            /* Forms exceptions */
            #per_page, .dropdown-menu, .form-control,
            .select2-container--default, .select2-container--classic,
            .select2-container--bootstrap, .select2-selection--single,
            .select2-selection--multiple, .select2-search--dropdown,
            .select2-search__field, .select2-search--inline,
            .select2-close-mask, .select2-dropdown
        ) {
            filter: invert(1) hue-rotate(180deg);
            color: initial;
        }
    }
}
```

**Comment by u1735067** [comment]
This issue still affects Nautobot v2(.4.12), for this versions the fix seems to be:

```css
:root {
    color-scheme: light dark;
}
html[data-theme="light"] {
    color-scheme: light;
}
html[data-theme="dark"] {
    color-scheme: dark;
}
```
in the base CSS.
