### ISSUE TITLE
Allow different concurrent development environments on a single machine

### ISSUE THREAD

**Issue by jifox** [nautobot/nautobot#615]
### Environment
* Python version: 3.8.5
* Nautobot version: 57c8b8f1e8cc (v1.0.4b1)

### Proposed Functionality

The `project_name` specified within "invoke" should be taken into account when building the docker image with `invoke build`

### Use Case

As a developer I want to be able to have different development environments on the developers machine (different projects).

The problem with the current `invoke build` version ist, that the container image name will not be affected by the `docker-compose --project-name ...` parameter because it is fully specified as image name in docker-compose.yml file. Thus overwriting the image of all the other project when `invoke build` is executed.

```yaml
services:
  nautobot:
    build:
      args:
        PYTHON_VER: "${PYTHON_VER}"
      context: ../
      dockerfile: docker/Dockerfile
      target: dev
    image: "networktocode/nautobot-dev-py${PYTHON_VER}:local"
    ports:
      - "8000:8080"
    depends_on:
      - postgres
```

### Database Changes

None

### External Dependencies

None
