### ISSUE TITLE
Unable to Assign IP to device using Ansible

### ISSUE THREAD

**Issue by nerdfunk-net** [nautobot/nautobot#7351]
### Environment
* Nautobot version (Docker tag too if applicable): 2.4.7
* Python version: 3.12
* Database platform, version: postgres 16
* Middleware(s):

### Steps to Reproduce
1. Use the following Ansible Playbook to add device, interface and assign an IP-Address

```
- name: Add IP Address to nautobot IPAM
  networktocode.nautobot.ip_address:
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    address: "{{ interface_ip_address }}"
    namespace: Global
    status: Active
    state: present
  register: ip_address_result

- name: add device to nautobot
  networktocode.nautobot.device:
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    name: "{{ device_name}}"
    device_type: "{{ device_type }}"
    role: "{{ device_role }}"
    location: "{{ device_location }}"
    status: Active
    state: present

- name: Create interface 
  networktocode.nautobot.device_interface:
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    device: "{{ device_name}}"
    name: "{{ device_interface }}"
    type: "{{ interface_type }}"
    status: Active
    state: present

- name: Assign IP Address to Device
  networktocode.nautobot.ip_address_to_interface:
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    ip_address:
      address: "{{ interface_ip_address }}"
      namespace: "Global"
    interface:
      name: "{{ device_interface }}"
      device: "{{ device_name}}"

```

### Expected Behavior
The device and the interface is added and the IP address is assigned.

### Observed Behavior
The device and the interface is added but the IP address is not assigned.

The following error occurs:

```
TASK [Assign IP Address to Device] *********************************************************************************************
fatal: [lab]: FAILED! => {"changed": false, "msg": "{\"ip_address\":[\"“address” is not a valid UUID.\"]}"}

```

The following workaround works:

```
- name: Assign IP Address to Device
  networktocode.nautobot.ip_address_to_interface:
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    ip_address: "{{ ip_address_result.ip_address.id }}"
    interface:
      name: "{{ device_interface }}"
      device: "{{ device_name}}"

```
