### ISSUE TITLE
Unknown command: 'post_upgrade'

### ISSUE THREAD

**Issue by FloLaco** [nautobot/nautobot#786]
### Environment
* Python version: Python 3.6.14
* Nautobot version: 
```
nautobot-server --version
1.1.1
```
* Docker-image : networktocode/nautobot

### Steps to Reproduce
1. docker-compose up -d
2. container failed because `docker-entrypoint.sh` try `nautobot-server post_upgrade` which does not working
3.

### Expected Behavior
Post_upgrade proceed

### Observed Behavior
```
Unknown command: 'post_upgrade'
Type 'nautobot-server help' for usage.
⏳ Waiting on DB... (0s / 30s)
Unknown command: 'post_upgrade'
Type 'nautobot-server help' for usage.
⏳ Waiting on DB... (3s / 30s)
Unknown command: 'post_upgrade'
Type 'nautobot-server help' for usage.
⏳ Waiting on DB... (6s / 30s)
Unknown command: 'post_upgrade'
Type 'nautobot-server help' for usage.
⏳ Waiting on DB... (9s / 30s)
Unknown command: 'post_upgrade'
Type 'nautobot-server help' for usage.
⏳ Waiting on DB... (12s / 30s)
Unknown command: 'post_upgrade'
Type 'nautobot-server help' for usage.
⏳ Waiting on DB... (15s / 30s)
Unknown command: 'post_upgrade'
Type 'nautobot-server help' for usage.
⏳ Waiting on DB... (18s / 30s)
Unknown command: 'post_upgrade'
Type 'nautobot-server help' for usage.
⏳ Waiting on DB... (21s / 30s)
Unknown command: 'post_upgrade'
Type 'nautobot-server help' for usage.
⏳ Waiting on DB... (24s / 30s)
Unknown command: 'post_upgrade'
Type 'nautobot-server help' for usage.
⏳ Waiting on DB... (27s / 30s)
Unknown command: 'post_upgrade'
Type 'nautobot-server help' for usage.
❌ Waited 30s or more for the DB to become ready.
```

My debug : 
```
florian@dsrauto-dev1:~/nautobot-carrefour$ docker exec -it nautobot /bin/bash
nautobot@2db08bf4b155:~$ nautobot-server post_upgrade
Unknown command: 'post_upgrade'
Type 'nautobot-server help' for usage.
nautobot@2db08bf4b155:~$ env
PYTHONUNBUFFERED=1
HOSTNAME=2db08bf4b155
PYTHON_VERSION=3.6.14
PWD=/opt/nautobot
HOME=/opt/nautobot
NAUTOBOT_ROOT=/opt/nautobot/
LANG=C.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
GPG_KEY=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D
TERM=xterm
prometheus_multiproc_dir=/prom_cache
SHLVL=1
PYTHON_PIP_VERSION=21.2.2
PYTHON_GET_PIP_SHA256=6665659241292b2147b58922b9ffe11dda66b39d52d8a6f3aa310bc1d60ea6f7
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/a1675ab6c2bd898ed82b1f58c486097f763c74a9/public/get-pip.py
NAUTOBOT_DEBUG=True
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env
nautobot@2db08bf4b155:~$ which nautobot-server
/usr/local/bin/nautobot-server
```

`docker-compose.yml`
```
version: "3.7"

services:

  redis_s:
    build: ./redis_s
    image: carrefourdsr/redis
    container_name: redis_s_nautobot
    ports :
     - "6379"

  redis-sentinel:
    image: docker.io/bitnami/redis-sentinel:latest
    container_name: redis_sentinel_nautobot
    environment:
      - REDIS_MASTER_HOST=redis_s_nautobot

  nautobot:
    image: "networktocode/nautobot"
    volumes:
      - ./nautobot/nautobot_config.py:/opt/nautobot/nautobot_config.py:ro
    environment:
      - NAUTOBOT_ROOT=/opt/nautobot/
      - NAUTOBOT_DEBUG=True
    container_name: nautobot

  sql:
    image: postgres:11
    restart: always
    container_name: sql-nautobot
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: cisco1234
      POSTGRES_DB: nautobot

```

Official docker image : 
```
networktocode/nautobot                                                                          latest              b778847db723        19 hours ago        372MB
```
