### ISSUE TITLE
Allow JSONSchema Custom Definitions to be tied to schemas for config contexts

### ISSUE THREAD

**Issue by FragmentedPacket** [nautobot/nautobot#967]
### Environment
* Python version: 3.6
* Nautobot version: 1.1.3

### Proposed Functionality
Potentially create a new model to store definitions that can be referenced within schemas.

An example of what we have are the following:

**property**:

```yaml
---
zip_code:
  oneOf:
    - type: "integer"
      min: 10000
      max: 99999
    - type: "string"
      pattern: "^[0-9]{5}(-[0-9]{4})?$"
    - type: "string"
      pattern: "^(?!.*[DFIOQU])[A-VXY][0-9][A-Z]\\s?[0-9][A-Z][0-9]$"
```

**object**:

```yaml
---
lan_network:
  type: "object"
  properties:
    address:
      $ref: "../properties/ip.yml#ipv4_subnet"
    enable:
      type: "boolean"
  required:
    - "address"
    - "enable"
```

The object one also shows a ref to something existing so we'd want to re-use these within different aspects.

### Use Case
We use custom JSON Schema definitions for both properties and objects and would like to move schema validation into the config contexts.

### Database Changes
Potentially a new model for storing definitions of objects/properties

### External Dependencies
N/A
